[main]
font=IntoneMonoNF:size=15
use-bold=yes
prompt=""
match-counter=no
anchor=left
lines=10
width=15
horizontal-pad=20
inner-pad=5
#auto-select=yes

[colors]
background=272e33e0
text=d3c6aaff
prompt=a7c080ff
placeholder=d3c6aaff
input=d3c6aaff
match=a7c080ff
selection=a7c080ff
selection-text=272e33dd
selection-match=c65e60ff
counter=7f849cff
border=74c7ecff

[border]
width=0
radius=20
selection-radius=5
