font_family FantasqueSansM Nerd Font Mono
# Intone Mono
#
# FantasqueSansM
# MonaspiceNe
# MonaspiceKr
# Hurmit
# fc-list | sed 's/^[^:]*//' | sed 's/:style.*//' | cut -c 3- | sed 's/,.*//' | sort | uniq | nl | more

font_size 18.0
adjust_line_height 2
bold_font auto
italic_font auto
bold_italic_font auto

background_opacity 0.9

enable_audio_bell no

shell /run/current-system/sw/bin/fish
confirm_os_window_close 0

background #272e33
foreground #d3c6aa

color0 #414b50
color1 #e67e80
color2 #a7c080
color3 #dbbc7f
color4 #7fbbb3
color5 #d599b6
color6 #83c092
color7 #d3c6aa

color8  #475258
color9  #e67e80
color10 #a7c080
color11 #dbbc7f
color12 #7fbbb3
color13 #d599b6
color14 #83c092
color15 #d3c6aa
