#!/usr/bin/env bash
# Automates the usage of rebuild&switching using param for flake commits
cd /home/jacob/NixOS/
clear
echo "Current changes:"
git diff -w --stat
printf "\nEnter commit message below (Ctrl+D to finish):\n"
commitmsg=""
while IFS= read -r line </dev/tty; do
  commitmsg+="$line"$'\n'
done

clear
printf "Confirm message:\n\n$commitmsg\n"
read -t 15 -n 1 -p "Does this look right?(Y/y) " confirm
printf "\n\n"

if [[ $confirm == "y" || $confirm == "Y" ]]; then
  cd /home/jacob/NixOS || exit 1
  printf "Authenticating...\n"
  git add .
  git commit -m "$commitmsg"
  nixos-rebuild switch --flake /home/jacob/NixOS#nixos-btw
  nix-env --delete-generations +5
fi
