#!/usr/bin/env bash
# Automates the usage of rebuild&switching using param for flake commits
cd ~/NixOS/
clear
echo "Current changes:"
git diff -w --stat
printf "\nEnter commit message below (Ctrl+D to finish):\n"
commitmsg=""
while IFS= read -r line < /dev/tty; do
    commitmsg+="$line"$'\n'
done

clear
printf "Confirm message:\n\n$commitmsg\n"
read -t 15 -n 1 -p "Does this look right?(Y/y) " confirm
printf "\n\n"

if [[ $confirm == "y" || $confirm == "Y" ]]; then
    cd ~/NixOS || exit 1
    git add .
    git commit -m "$commitmsg"
    sudo nixos-rebuild switch --flake ~/NixOS#nixos-btw
    nix-env --delete-generations +5
fi
