#!/usr/bin/env bash
# Automates the usage of rebuild&switching using param for flake commits
if [[ $# != 1 ]]; then
    echo "Usage: $0 COMMIT_MSG" 
else
    printf "\n%s\n" "$1"
    read -t 5 -n 1 -p "Confirm commit message?(Y/y)" confirm

    if [[ $confirm == "y" || $confirm == "Y" ]]; then
        cd ~/NixOS || exit 1
        git add .
        git commit -m "$1"
        sudo nixos-rebuild switch --flake ~/NixOS#nixos-btw
        nix-env --delete-generations +5
    fi
fi
