# https://yazi-rs.github.io/docs/configuration/yazi
[mgr]
ratio = [1,4,3]
sort_by = "alphabetical"
sort_dir_first = true
linemode = "size"
show_hidden = false
show_symlink = true
scrolloff = 5

[preview]
wrap = "yes"
tab_size = 3
# max_width
# max_height
image_delay = 75
image_filter = "triangle"
image_quality = 75

[opener]
# VLC for video/music
play = [
    { run = "vlc %s", orphan = true, for = "unix" }
]
# NeoVIM for editing
edit = [
    { run = "nvim %s", block = true, for = "unix" }
]
# GIMP for images
# open = [
